---
engines:
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - '**.rb'
exclude_paths:
- pkg/
- spec/
